//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarchim.Models.database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JarchimDb : DbContext
    {
        public JarchimDb()
            : base("name=JarchimDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_about> tbl_about { get; set; }
        public virtual DbSet<tbl_ad> tbl_ad { get; set; }
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_city> tbl_city { get; set; }
        public virtual DbSet<tbl_comment> tbl_comment { get; set; }
        public virtual DbSet<tbl_contact> tbl_contact { get; set; }
        public virtual DbSet<tbl_copen> tbl_copen { get; set; }
        public virtual DbSet<tbl_img_ad> tbl_img_ad { get; set; }
        public virtual DbSet<tbl_newsletter> tbl_newsletter { get; set; }
        public virtual DbSet<tbl_order> tbl_order { get; set; }
        public virtual DbSet<tbl_rating> tbl_rating { get; set; }
        public virtual DbSet<tbl_shopping_cart> tbl_shopping_cart { get; set; }
        public virtual DbSet<tbl_slider> tbl_slider { get; set; }
        public virtual DbSet<tbl_temp_shopping> tbl_temp_shopping { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
    }
}
