//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarchim.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_category
    {
        public int cat_id { get; set; }
        public string cat_title { get; set; }
        public Nullable<int> top_id { get; set; }
        public string cat_href { get; set; }
        public string cat_baner_img { get; set; }
        public string cat_icon_img { get; set; }
    }
}
