//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarchim.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rating
    {
        public double rat_id { get; set; }
        public Nullable<long> ad_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<decimal> star_count { get; set; }
    }
}
