//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarchim.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_img_ad
    {
        public long img_id { get; set; }
        public long ad_id { get; set; }
        public string ad_img { get; set; }
        public string ad_img_title { get; set; }
        public string ad_img_alt { get; set; }
    }
}
