//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarchim.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comment
    {
        public int comment_id { get; set; }
        public Nullable<int> ad_id { get; set; }
        public Nullable<int> top_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_text { get; set; }
        public string user_ip_addr { get; set; }
        public Nullable<System.DateTime> comment_date { get; set; }
        public Nullable<bool> c_confirm { get; set; }
        public Nullable<bool> c_read { get; set; }
        public Nullable<int> c_like { get; set; }
        public Nullable<int> c_dislike { get; set; }
    }
}
