//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarchim.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_contact
    {
        public long contact_id { get; set; }
        public string contact_name { get; set; }
        public string contact_email { get; set; }
        public string contact_phone { get; set; }
        public string contact_text { get; set; }
        public Nullable<bool> contact_is_read { get; set; }
        public Nullable<System.DateTime> contact_date { get; set; }
        public string contact_subject { get; set; }
    }
}
