//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarchim.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_temp_shopping
    {
        public long temp_id { get; set; }
        public Nullable<int> cart_id_get { get; set; }
        public Nullable<int> ad_id { get; set; }
        public Nullable<int> temp_count { get; set; }
        public Nullable<System.DateTime> temp_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public string trans_id { get; set; }
    }
}
